import 'recipe_db.dart';
import 'dart:convert';

/*
Class to load the recipes into the recipe database
*/
class LoadRecipes {
  LoadRecipes._privateConstructor();
  static final LoadRecipes instance = LoadRecipes._privateConstructor();

  Future<void> loadRecipes() async {
    try {
      await RecipeDB.instance.populateDatabase(recipes);
      print('Recipes successfully loaded into the database.');
    } catch (e) {
      print('Error loading recipes: $e');
    }
  }
}

//list of the app's recipes
final List<Map<String, dynamic>> recipes = [
  {
    'id': 1,
    'title': 'Gyudon',
    'ingredients': jsonEncode([
      'soy sauce',
      'sugar',
      'mirin',
      'seasoned rice wine',
      'sake', 
      'rice wine',
      'dashi broth',
      'ginger',
      'onion',
      'thinly sliced beef',
      'eggs',
      'rice',
      'benishoga', 
      'pickled ginger',
      'green onion',
      'shichimi togarashi'
    ]),
    'instructions': jsonEncode([
      'In a large skillet, combine soy sauce, sugar, mirin, sake, dashi, and ginger.', 
      'Bring to a boil over high heat.',
      'Reduce heat to medium-high and add sliced onion.', 
      'Cover and simmer for 1 minute.',
      'Remove ginger slices and add thinly sliced beef.', 
      'Stir occasionally to cook evenly.',
      'After 4 minutes or when beef is 3/4 cooked, crack eggs into the skillet and cover for desired doneness.',
      'Serve over rice with pickled ginger, green onions, and shichimi to taste.'
    ]),
    'image' : 'assets/images/gyudon.webp',
    'tags' : jsonEncode(['beef', 'eggs', 'rice', 'asian', 'japanese']),
  },
  {
    'id': 2,
    'title': 'Jamaican Oxtail',
    'ingredients': jsonEncode([ 
      'oxtail',
      'soy sauce',
      'Worcestershire sauce',
      'onion',
      'garlic',
      'browning sauce',
      'thyme',
      'scotch bonnet pepper',
      'carrots',
      'butter beans',
      'beef broth'
    ]),
    'instructions': jsonEncode([
      'Marinate oxtail with soy sauce, Worcestershire sauce, and seasonings for at least 1 hour.',
      'In a pot, brown oxtail on all sides, then add onions, garlic, and thyme.',
      'Add beef broth, carrots, and scotch bonnet pepper. Simmer for 2-3 hours until tender.',
      'Add butter beans and cook for another 15 minutes.',
      'Serve hot with rice and peas.'
    ]),
    'image' : 'assets/images/oxtail.jpg',
    'tags' : jsonEncode(['oxtail', 'jamaican', 'caribbean', 'beans']),
  },
  {
    'id': 3,
    'title': 'Jamaican Curry Chicken',
    'ingredients': jsonEncode([
      'chicken',
      'jamaican curry powder',
      'allspice', 
      'adobo seasoning', 
      'turmeric', 
      'thyme', 
      'salt',
      'black pepper',
      'Onion', 
      'scotch bonnet pepper',
      'carrots', 
      'garlic', 
      'ginger', 
      'green onion', 
      'potatoes',
      'coconut milk',
      'olive oil',
      'hot sauce',
    ]),
    'instructions': jsonEncode([
      'Cut up the chicken into smaller pieces and add to a large bowl.',
      'Season the Chicken. Rub the chicken pieces with 2 tablespoons Jamaican curry powder, adobo seasoning, allspice, dried thyme, turmeric, and salt and pepper to taste.',
      'Cook the Vegetables. Heat the oil in a large pot or Dutch oven over medium heat or medium-high heat.',
      'Add the onion and peppers, and cook them down 5 minutes to soften.',
      '"Burn the Curry". Add the garlic, ginger, and 2 tablespoons Jamaican curry powder.', 
      'Cook for 2 minutes in the oil to let the seasoning bloom.',
      'This is called "Burning the Curry", which isn\'t actually burning it, but cooking out the raw seasoning flavor.',
      'Brown the Chicken. Add the chicken and cook for 10 minutes to brown all sides, flipping half way through.',
      'NOTE that the chicken may release liquid, which you can keep in the pan for simmering, though you may want to adjust how much liquid you add later.',
      'Liquids and Potatoes. Stir in the coconut milk or chicken broth, potatoes, and carrots.', 
      'Taste and adjust with salt, pepper and hot sauce to your personal tastes.',
      'Add a few sprigs of fresh thyme here if you\'d like.',
      'Cover and Simmer. Cover the curry and reduce the heat. Simmer for 20 to 30 minutes, or until the vegetables are done and the chicken is tender and cooked through.',
      'It should measure 165 degrees F internal when measured with a meat thermometer.',
      'Serve! I like to garnish mine with fresh chopped parsley and red pepper flakes.',
      'Boom! Done! Jamaican curry chicken is ready to serve! Looks wonderful, doesn\'t it? I\'m sure your kitchen smells awesome.',
    ]),
    'image' : 'assets/images/curry.jpg',
    'tags' : jsonEncode(['chicken', 'curry', 'potato', 'jamaican', 'caribbean']),
  },
  {
    'id': 4,
    'title': 'Katsudon',
    'ingredients': jsonEncode([
      'dashi',
      'soy sauce',
      'sake',
      'sugar',
      'mirin',
      'yellow onion',
      'pork cutlet',
      'eggs',
      'green onions',
      'white rice',
    ]),
    'instructions': jsonEncode([
      'Combine dashi, soy sauce, sake, sugar, and mirin in a small saucepan or donburi pan and bring to a simmer over medium heat.',
      'If using onion, add to broth and simmer until tender, about 5 minutes.',
      'Add sliced fried cutlet and let simmer for 1 minute.',
      'Meanwhile, beat together eggs and scallions in a small bowl.', 
      'Pour egg mixture on top of cutlet and around broth.',
      'Cover and cook until eggs are as set as you\'d like them, about 1 minute for very soft or 2 minutes for medium.',
      'Slide broth, egg, and chicken out on top of a bowl of rice. Sprinkle with scallions and serve.',
    ]),
    'image' : 'assets/images/katsudon.jpg',
    'tags' : jsonEncode(['pork', 'eggs', 'rice', 'asian', 'japanese']),
  },
  {
    'id': 5,
    'title': 'Pasta Carbonara',
    'ingredients': jsonEncode([
      'bacon',
      'garlic',
      'linguine',
      'parmesan',
      'eggs',
      'salt',
      'pepper',
      'fresh parsley',
    ]),
    'instructions': jsonEncode([
      'Add bacon and water to a skillet and bring to a simmer.',
      'Continue simmering until water is evaporated, then continue to cook the bacon until crispy.',
      'Remove bacon from pan and reserve the drippings.',
      'Saute garlic in that same skillet until golden brown, then add to a bowl with 1 tablespoon bacon fat, eggs, egg yolk, Parmesan and pepper. Mix well.',
      'Meanwhile, cook the spaghetti or linguine pasta until al dente.', 
      'Once cooked, drain pasta and reserve 1 cup of the cooking water.',
      'Slowly pour the hot cooking water into the egg mixture.', 
      'Then pour over the hot pasta and toss to coat. Add crumbled bacon.',
      'Let pasta rest for a few minutes, tossing frequently until the carbonara sauce thickens.', 
      'Serve immediately with a sprinkle of fresh parsley.',
    ]),
    'image' : 'assets/images/carbonara.jpg',
    'tags' : jsonEncode(['bacon', 'eggs', 'pasta', 'parmesan', 'pork']),
  },
  {
    'id' : 6,
    'title' : 'Lasagna',
    'ingredients': jsonEncode([
      'yellow onion',
      'olive oil',
      'ground beef',
      'salt',
      'black pepper',
      'marinara sauce',
      'mozzarella cheese',
      'lasagna noodles',
      'ricotta cheese',
    ]),
    'instructions': jsonEncode([
      'Heat the oven to 400ºF. Arrange a rack in the middle of the oven and heat the oven to 400°F.',
      'Brown the beef and onion. Finely chop 1 medium yellow onion. Heat 1 tablespoon olive oil in a 12-inch or larger regular or cast iron skillet over medium-high heat until shimmering.', 
      'Add the onion, 1 pound lean ground beef, 1/2 teaspoon kosher salt, and 1/4 teaspoon freshly ground black pepper, and cook, breaking the beef up into small pieces with a wooden spoon, until the beef is cooked through, 6 to 8 minutes.', 
      'Remove from the heat and let cool for 5 minutes.',
      'Prepare the baking dish and assemble the meat sauce. Open 1 (24 to 25-ounce) jar marinara sauce (3 cups). Spread a thin layer of the sauce in the bottom of a 9x13-inch baking dish. Stir the remaining sauce into the ground beef mixture.',
      'Begin layering the lasagna. Shred 12 ounces low-moisture mozzarella cheese if needed (3 cups).', 
      'Place 5 lasagna noodles in the baking dish, breaking them if needed to create a single layer (it’s OK if the noodles overlap slightly).', 
      'Dollop and spread 1 cup of the ricotta cheese over the noodles.', 
      'Dollop and spread about 1 1/2 cups of the meat sauce on the ricotta, then sprinkle with 1 cup of the mozzarella.',
      'Continue layering the lasagna. Arrange 5 more noodles over the mozzarella, followed by 1 cup of the ricotta cheese, 1 1/2 cups of the meat sauce, and 1 cup of the mozzarella.',
      'Top with a final layer of 5 noodles and the remaining sauce, spreading the sauce thin so that it almost completely covers the noodles. (Reserve the remaining 1 cup mozzarella for the end of baking.) Cover the dish tightly with aluminum foil.',
      'Bake the lasagna for 1 hour. Bake for 1 hour. Check to make sure the noodles are done by poking the lasagna with a knife; the knife should slide easily through all the layers. If it doesn\'t, cover and cook for 15 minutes more.',
      'Sprinkle with the remaining mozzarella and finish baking. Uncover the lasagna and sprinkle with the remaining 1 cup mozzarella.', 
      'Bake uncovered until the mozzarella is melted and lightly browned, and the sauce is bubbling, 8 to 10 minutes more.Let pasta rest for a few minutes, tossing frequently until the carbonara sauce thickens.', 
      'Serve immediately with a sprinkle of fresh parsley.',
      'Cool the lasagna for 15 minutes. Let the lasagna cool on a wire rack for at least 15 minutes before serving.',
    ]),
    'image' : 'assets/images/lasagna.webp',
    'tags' : jsonEncode(['cheese', 'beef', 'pasta', 'parmesan', 'marinara', 'mozarella cheese', 'ricotta cheese', 'lasagna']),
  },
  {
    'id' : 7,
    'title' : 'Falafel',
    'ingredients': jsonEncode([
      'chickpeas',
      'shallot',
      'garlic',
      'lemon',
      'cumin',
      'coriander',
      'cayenne',
      'salt',
      'baking powder',
      'cilantro',
      'parsley',
      'olive oil',
    ]),
    'instructions': jsonEncode([
      'The first step to this method for how to make falafel is soaking the chickpeas.', 
      'You’ll need to plan ahead here. The chickpeas need to soak for 24 hours, or at least overnight, before you form the balls.', 
      'Drain and rinse them before proceeding with the recipe.',
      'Once the chickpeas soak, pulse them together with the other ingredients.', 
      'Add the chickpeas to the food processor with the shallot, garlic, herbs, spices, lemon zest, baking powder, olive oil, and salt.',
      'Process until the ingredients are finely ground, but not pureed.',
      'Next, form the falafel balls. Scoop up the chickpea and herb mixture with a 2-tablespoon cookie scoop, then use your hands to form it into balls or patties.', 
      'If they’re not holding together, give the mixture a few more pulses in the food processor.',
      'Finally, bake! Arrange the patties on a parchment-lined baking sheet, and drizzle them generously with olive oil.', 
      'Seriously, don’t hold back on the oil here! We’re not frying, remember, so a good drizzle of oil is essential for helping the balls bake up nice and crisp.',
      'Transfer the pan to a 400°F oven. Bake for 14 minutes, then flip and bake until the falafel is golden brown and crisp. That’s it!',
    ]),
    'image' : 'assets/images/falafel.jpg',
    'tags' : jsonEncode(['falafel', 'chickpeas', 'vegetarian', 'garlic', 'shallot', 'middle eastern']),
  },
  {
    'id' : 8,
    'title' : 'Frittata',
    'ingredients': jsonEncode([
      'eggs',
      'milk',
      'garlic',
      'salt',
      'black pepper',
      'olive oil',
      'green onion',
      'broccoli',
      'paprika',
      'feta cheese',
    ]),
    'instructions': jsonEncode([
      'Preheat the oven to 400°F.',
      'Whisk the eggs, almond milk, garlic, and salt until well combined. Set aside. Choose a vegetable variation. Follow the corresponding instructions to make it.',
      'Heat 1 tablespoon olive oil in a 10 or 12-inch cast-iron skillet over medium heat. Add the scallions, broccoli, and a pinch of salt and pepper and cook, stirring occasionally, until the broccoli is tender but still bright green, 5 to 8 minutes.', 
      'Stir in the smoked paprika, then add the egg mixture and gently shake the pan to distribute.', 
      'Sprinkle with the feta and bake 15 to 20 minutes or until the eggs are set. Season to taste and serve.',
    ]),
    'image' : 'assets/images/frittata.jpg',
    'tags' : jsonEncode(['frittata', 'eggs', 'vegetarian', 'garlic', 'milk', 'broccoli', 'feta', 'vegetarian', 'breakfast', 'cheese',]),
  },
  {
    'id' : 9,
    'title' : 'Eggplant Parmesan',
    'ingredients': jsonEncode([
      'eggplant',
      'milk',
      'eggs',
      'parmesan cheese',
      'panko breadcrumbs',
      'oregano',
      'thyme',
      'red pepper flakes',
      'salt',
      'black pepper',
      'olive oil',
      'marinara sauce',
      'mozarella cheese',
      'basil',
    ]),
    'instructions': jsonEncode([
      'Preheat the oven to 400°F and line 2 baking sheets with parchment paper.',
      'In a medium-sized shallow dish, whisk the eggs and milk.',
      'In another medium-sized shallow dish, combine the panko, 1 cup Parmesan cheese, oregano, thyme, red pepper flakes, salt, and several grinds of pepper.', 
      'Dip the eggplant slices into the egg mixture and then into the panko mixture. Place onto the baking sheets, drizzle with olive oil, and bake for 18 minutes or until tender and golden brown.', 
      'In an 8x12 or 9x13-inch baking dish, spread ½ cup marinara, layer half the eggplant, and top with 1 cup of marinara and half the mozzarella.', 
      'Repeat with the remaining eggplant, the remaining marinara, and the remaining mozzarella.', 
      'Sprinkle with the remaining ¼ cup Parmesan cheese, drizzle with olive oil, and sprinkle with a few more pinches of sea salt.', 
      'Bake for 20 minutes or until the cheese is nicely melted.', 
      'Turn the oven to broil and broil for 2 to 4 or until the cheese is browned and bubbling.',
      'Remove from the oven and top with fresh basil.',
    ]),
    'image' : 'assets/images/eggplant-parmesan.jpg',
    'tags' : jsonEncode(['eggplant', 'eggs', 'vegetarian', 'mozarella', 'marinara', 'paremsan', 'panko', 'milk', 'cheese',]),
  },
  {
    'id' : 10,
    'title' : 'Pasta Primavera',
    'ingredients': jsonEncode([
      'pasta',
      'garlic',
      'squash',
      'zucchini',
      'asparagus',
      'cherry tomato',
      'red pepper flakes',
      'salt',
      'black pepper',
      'olive oil',
      'peas',
      'pecorino cheese',
      'lemon juice',
      'basil',
      'tarragon',
    ]),
    'instructions': jsonEncode([
      'Bring a large pot of salted water to a boil.', 
      'Prepare the pasta according to the package instructions, cooking until al dente.', 
      'Drain and toss with a drizzle of olive oil to prevent sticking.',
      'Heat the oil in a large, deep skillet over medium heat.', 
      'Add the garlic, squash, zucchini, asparagus, tomatoes, onion, salt, and several grinds of pepper and sauté for 3 to 4 minutes, or until the vegetables are tender.',
      'Add the pasta, peas, cheese, lemon juice, and a pinch of red pepper flakes and toss to combine.', 
      'Stir in the basil and tarragon, if using.',
      'Season to taste, garnish with more basil, and serve.',
    ]),
    'image' : 'assets/images/pasta-primavera.jpg',
    'tags' : jsonEncode(['pasta', 'pecorino', 'vegetarian', 'garlic', 'asparagus', 'zucchini', 'squash', 'cheese', 'cherry tomato',]),
  },
  {
    'id' : 11,
    'title' : 'Baked Salmon',
    'ingredients': jsonEncode([
      'light brown sugar',
      'paprika',
      'garlic powder',
      'cayenne pepper',
      'kosher salt',
      'ground black pepper',
      'panko breadcrumbs',
      'parsley leaves',
      'unsalted butter',
      'salmon fillet',
      'dijon mustard',
    ]),
    'instructions': jsonEncode([
      'Preheat oven to 425 degrees F.',
      'Line a baking sheet with foil.',
      'Mix the brown  sugar, paprika, garlic powder, cayenne pepper, 1 teaspoon kosher salt and a generous amount of freshly ground black pepper.',
      'Mix the panko with the parsley, butter, 1/4 teaspoon kosher salt and a few grinds of black pepper.',
      'Place the salmon skin-side down on the prepared baking sheet',
      'Spread the surface of the fish with the dijon then press the brown sugar mixture all over the salmon then top with the breadcrumb mixture.',
      'Crimp all four sides of the foil to create a border around the salmon.',
      'Bake 15 - 18 minutes until the breadcrumbs are golden brown, and the salmon is firm and flakes easily when pressed.',
      'Cut into four equal portions for serving.',
    ]),
    'image' : 'assets/images/baked-salmon.jpg',
    'tags' : jsonEncode(['salmon', 'fish', 'seafood', 'brown pepper', 'cayenne pepper', 'bread crumbs', 'butter', 'brown sugar', 'dijon mustard',]),
  },
  {
    'id' : 12,
    'title' : 'Meat Loaf',
    'ingredients': jsonEncode([
      'olive oil',
      'yellow onions',
      'thyme',
      'kosher salt',
      'ground black pepper',
      'worcestershire sauce',
      'chicken stock',
      'tomato paste',
      'ground chuck',
      'dry bread crumbs',
      'eggs',
      'ketchup',
    ]),
    'instructions': jsonEncode([
      'Preheat the oven to 325 degrees F.',
      'Heat the olive oil in a medium saute pan.',
      'Add the onions, thyme, salt, and pepper and cook over medium-low heat, stirring occasionally, for 8 to 10 minutes.',
      'Off the heat, add the Worcestershire sauce, chicken stock, and tomato paste.',
      'Allow to cool slightly.',
      "In a large bowl, combine the ground chuck, onion mixture, bread crumbs, and eggs, and mix lightly with a fork. Don't mash or the meat loaf will be dense.",
      'Shape the mixture into a rectangular loaf on a sheet pan covered with parchment paper.',
      'Spread the ketchup evenly on top.',
      'If possible, add a pan of hot water in the oven, under the meat loaf, to keep the top from cracking.',
      'Bake for 1 to 1 1/4 hours, until the internal temperature is 160 degrees F and the meat loaf is cooked through.',
      'Serve hot.',
    ]),
    'image' : 'assets/images/meatloaf.jpg',
    'tags' : jsonEncode(['meatloaf', 'meat', 'loaf', 'olive oil', 'onions', 'black pepper', 'chicken stock', 'tomato paste', 'ketchup', 'bread crumbs', 'eggs', 'ketchup',]),
  },
  {
    'id' : 13,
    'title' : 'Scalloped Potatoes',
    'ingredients': jsonEncode([
      'butter',
      'russet potatoes',
      'heavy cream',
      'whole milk',
      'minced garlic',
      'thyme',
      'kosher salt',
      'ground black pepper',
      'grated nutmeg',
      'gruyere cheese',
      'parmesean cheese',
    ]),
    'instructions': jsonEncode([
      'Preheat the oven to 350 degrees F.',
      'Grease an 8-inch square baking dish with unsalted butter.',
      'Peel the potatoes and cut them into 1/8-inch-thick slices.',
      'Add the sliced potatoes, heavy cream, whole milk, 2 tablespoons butter, garlic, thyme, 1 1/2 teaspoons salt, 1/2 teaspoon pepper and the nutmeg to a medium saucepan.',
      'Bring to a simmer over medium heat and cook, stirring occasionally, until the potatoes are tender and almost cooked through, about 5 minutes.',
      'Potatoes should not be soft and falling apart.',
      'Remove the saucepan from the heat.',
      'Add the Gruyere and Parmesan, stirring gently to combine.',
      'Pour the potato mixture into the prepared baking dish.',
      'Bake until the top is light golden brown and the potatoes are cooked through and tender, about 45 minutes.',
      'Let rest for 10 minutes before serving.',
    ]),
    'image' : 'assets/images/scalloped-potatoes.jpg',
    'tags' : jsonEncode(['scalloped potatoes', 'potatoes', 'american', 'cheesy', 'parmesean', 'gruyere', 'cheese', 'milk', 'cream', 'butter',]),
  },
  {
    'id' : 14,
    'title' : 'Beans, Greens, and Cream',
    'ingredients': jsonEncode([
      'butter',
      'minced shallot',
      'kosher salt',
      'ground black pepper',
      'minced garlic',
      'baby spinach',
      'shredded havarti cheese',
      'heavy cream',
      'navy beans',
      'lemon zest',
      'toasted bread',
    ]),
    'instructions': jsonEncode([
      'Melt the butter in a large skillet over medium heat.',
      'Add the shallot, a good pinch of salt and several grinds of pepper and cook, stirring occasionally, until tender and translucent, about 4 minutes.',
      'Add the garlic and continue to cook until tender and fragrant, about 1 minute more.',
      'Add a couple handfuls of spinach and cook, stirring frequently, until wilted, 1 to 2 minutes.',
      'Repeat, adding a couple handfuls of spinach at a time, until all the spinach has been added and is wilted and tender.',
      'Stir in the Havarti, cream, 1 teaspoon salt and several grinds of pepper.',
      'Bring to a simmer, then continue to cook until the cheese is melted and the sauce is smooth, about 2 minutes.',
      'Stir in the beans and lemon zest until well combined, then simmer until the beans have warmed through, 1 to 2 minutes more.',
      'Taste and adjust the seasoning with salt and pepper.',
      'Serve immediately with toasted crusty bread for dipping.',
    ]),
    'image' : 'assets/images/beans-greens-cream.jpg',
    'tags' : jsonEncode(['beans', 'greens', 'cream', 'vegan', 'butter', 'havarti', 'cheese',]),
  },
  {
    'id' : 15,
    'title' : 'Curried Chicken Thighs',
    'ingredients': jsonEncode([
      'vegetable oil',
      'butter',
      'chicken thigh',
      'salt',
      'ground black pepper',
      'chopped onion',
      'curry powder',
      'cayenne pepper',
      'ground cinnamon',
      'cumin',
      'carrots',
      'chicken stock',
      'broccoli florets',
      'heavy cream',
      'frozen peas',
      'rice',
    ]),
    'instructions': jsonEncode([
      'Heat oil in large skillet and stir in butter to melt.',
      'Season chicken thighs with salt and pepper.',
      'Cook thighs skin side down until golden brown.',
      'Flip chicken and continue to cook until golden brown.',
      'Remove chicken to a plate.',
      'Stir in onions and cook until tender.',
      'Stir in curry, cayenne, cinnamon and cumin and cook until aromas are released.',
      'Stir in carrots and toss to coat.',
      'Add chicken stock and bring to a simmer.',
      'Place chicken thighs back into skillet and stir in broccoli.',
      'Cover and simmer for 15 minutes to cook chicken.',
      'Stir in cream and peas. Season to taste.',
      'Serve with rice.',
    ]),
    'image' : 'assets/images/curried-chicken.jpg',
    'tags' : jsonEncode(['chicken', 'curry', 'thigh', 'indian',]),
  },
  {
    'id' : 16,
    'title' : 'Baked Ziti',
    'ingredients': jsonEncode([
      'olive oil',
      'ziti pasta',
      'kosher salt',
      'tomato sauce',
      'mozzarella cheese',
      'parmesan cheese',
      'ground black pepper',
      'crushed red pepper',
    ]),
    'instructions': jsonEncode([
      'Preheat the oven to 400 degrees F.',
      'Bring a large pot of water to a boil, salt generously and boil the pasta until al dente (tender but still slightly firm).',
      'Drain.',
      'Toss the cooked pasta with the tomato sauce, cubed mozzarella, half the Parmesan, all of the black pepper and crushed red pepper in a large bowl.',
      'Transfer the pasta to the prepared baking dish.',
      'Cover the top of the pasta with the sliced mozzarella and sprinkle with the remaining Parmesan.',
      'Bake until lightly browned and hot, about 30 minutes.',
      'Serve immediately.',
    ]),
    'image' : 'assets/images/baked-ziti.jpg',
    'tags' : jsonEncode(['baked', 'ziti', 'pasta', 'italian', 'american', 'tomato', 'sauce',]),
  },
  {
    'id' : 17,
    'title' : 'Spicy Pork Noodle Bowl',
    'ingredients': jsonEncode([
      'thin chinese noodles',
      'vegetable oil',
      'ground pork',
      'minced ginger',
      'chicken broth',
      'pickles',
      'pickle brine',
      'soy sauce',
      'sesame seeds',
      'chili-garlic sauce',
      'light brown sugar',
      'cucumbers',
      'chery tomatoes'
    ]),
    'instructions': jsonEncode([
      'Bring a large pot of water to a boil.',
      'Add the noodles and cook as the label directs.',
      'Drain and toss with 2 teaspoons vegetable oil.',
      'Heat 1 tablespoon vegetable oil in a large skillet over medium-high heat.',
      'Add the pork and 2 teaspoons ginger; cook, breaking up the meat with a wooden spoon, until lightly browned, about 3 minutes.',
      'Add the chicken broth, pickles and 2 tablespoons each pickle brine and soy sauce and cook, scraping up any browned bits, until the liquid evaporates, about 4 minutes.',
      'Meanwhile, puree 3 tablespoons toasted sesame seeds in a blender until finely ground, about 15 seconds.',
      'Add the remaining 3 tablespoons vegetable oil and puree until smooth.',
      'Add 1/4 cup water, the chili-garlic sauce, brown sugar and the remaining 1/4 cup soy sauce, 2 tablespoons pickle brine and 1 teaspoon ginger; puree until combined.',
      'Top each serving of noodles with the sesame dressing, pork, cucumbers and tomatoes.',
      'Sprinkle with the remaining 1 tablespoon sesame seeds.',
    ]),
    'image' : 'assets/images/spicy-pork-noodle-bowl.jpg',
    'tags' : jsonEncode(['spicy', 'pork', 'noodle', 'chinese', 'asian', 'ginger', 'pickle', 'brown sugar', 'cucumbers',]),
  },
  {
    'id' : 18,
    'title' : 'Smoky Pork Posole',
    'ingredients': jsonEncode([
      'dried chile peppers',
      'chicken broth',
      'vegetable oil',
      'smoked pork chops',
      'white onion',
      'chopped garlic',
      'bay leaf',
      'dried oregano',
      'ground cumin',
      'white hominy',
      'kosher salt',
      'ground black pepper',
      'radishes',
      'cilantro',
      'limes'
    ]),
    'instructions': jsonEncode([
      'Heat a medium saucepan over high heat until very hot, about 1 minute.',
      'Add the chiles and cook, pressing them down with a spatula, until browned in spots, about 1 minute.',
      'Add 1 cup chicken broth and bring to a boil.',
      'Remove from the heat and set aside.',
      'Heat the vegetable oil in a large pot or Dutch oven over high heat.',
      'Add the pork chop bones and cook, turning, until lightly browned on both sides, about 2 minutes.',
      'Add the onion, garlic and bay leaf and cook, stirring, until the onion is softened, about 2 minutes.',
      'Stir in the oregano and cumin and cook 30 seconds.',
      'Add the remaining 3 cups chicken broth and the hominy.',
      'Cover and bring to a simmer.',
      'Puree the chile-broth mixture in a blender until smooth; add to the pot.',
      'Continue to simmer, uncovered, 10 minutes.',
      'Discard the pork bones and bay leaf.',
      'Add the diced pork and cook until warmed through, about 5 minutes.',
      'Season with salt and pepper.',
      'Top each serving with diced onion, sliced radishes and cilantro. Serve with lime wedges.',
    ]),
    'image' : 'assets/images/smoky-pork-posole.jpg', 
    'tags' : jsonEncode(['pork', 'posole', 'mexican', 'latin', 'pepper', 'chile', 'cilantro', 'limes',]),
  },
  {
    'id' : 19,
    'title' : 'Sasusage Broccolini Pizza',
    'ingredients': jsonEncode([
      'olive oil',
      'pizza dough',
      'diced tomatoes',
      'basil',
      'ricotta cheese',
      'mozzarella cheese',
      'mint',
      'kosher salt',
      'ground black pepper',
      'italian sausages',
      'sliced garlic',
      'broccolini',
    ]),
    'instructions': jsonEncode([
      'Put an inverted baking sheet on the lowest oven rack; preheat to 475 degrees F.',
      'Line another inverted baking sheet with parchment; drizzle with 2 tablespoons olive oil.',
      'Form the pizza dough into an 8-inch oval on the parchment; flip to coat with the oil.',
      'Drape with plastic wrap; set aside.',
      'Combine the tomatoes and basil in a bowl.',
      'Mix the ricotta, mozzarella and mint in another bowl; season with 1/2 teaspoon salt and a few grinds of pepper.',
      'Heat the remaining 1 tablespoon olive oil in a skillet over medium-high heat.',
      'Add the sausages and garlic; cook, breaking up the meat, 5 minutes.',
      'Remove to a plate using a slotted spoon.',
      'Add the broccolini and 1/2 cup water to the drippings in the skillet and cook 5 minutes.',
      'Stretch the dough to 11 by 14 inches on the parchment; spoon the ricotta mixture on top.',
      'Top with the tomatoes, sausage and broccolini.',
      'Slide the pizza (on the parchment) onto the hot baking sheet.',
      'Bake until the crust is golden, 15 minutes.',
      'Transfer the pizza to a cutting board to slice.',
    ]),
    'image' : 'assets/images/sausage-broccolini-pizza.jpg',
    'tags' : jsonEncode(['sausage', 'broccolini', 'pizza', 'italian', 'cheese', 'garlic', 'olive oil', 'baked',]),
  },
  {
    'id' : 20,
    'title' : 'Tomato Soup and Croutons',
    'ingredients': jsonEncode([
      'olive oil',
      'yellow onions',
      'minced garlic',
      'chicken stock',
      'crushed tomatoes',
      'saffron threads',
      'kosher salt',
      'ground black pepper',
      'orzo',
      'heavy cream',
      'croutons',
    ]),
    'instructions': jsonEncode([
      'In a large pot or Dutch oven, heat the olive oil over medium heat.',
      'Add the onions and cook over medium-low heat for 15 minutes, stirring occasionally, until golden brown.',
      'Add the garlic and cook for 1 more minute.',
      'Stir in the chicken stock, tomatoes, saffron, 1 tablespoon salt and 1 teaspoon pepper.',
      'Bring the soup to a boil, then lower the heat and simmer for 15 minutes.',
      'Meanwhile, fill a medium pot with water, add 2 teaspoons salt and bring to a boil.',
      'Add the orzo and cook for 7 minutes. (It will finish cooking in the soup).',
      'Drain the orzo and add it to the soup.',
      'Stir in the cream, return the soup to a simmer and cook for 10 more minutes, stirring frequently.',
      'Serve hot with croutons scattered on top.',
    ]),
    'image' : 'assets/images/tomato-soup-with-croutons.jpg',
    'tags' : jsonEncode(['tomato', 'soup', 'croutons', 'italian', 'bowl', 'homemade', 'olive oil', 'orzo',]),
  },
];